[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["kota-karthik <kotakarthik2307@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
statsmodels = "^0.14.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
